### ISSUE TITLE
Flubu.Runner should check if target BuildScript.cs already exists.

### ISSUE THREAD

**Issue by zoroz** [flubu-core/flubu.core#20]
On nuget package update, flubu.runner script should check if BuildScript.cs already exists on target folder and should not try to overwrite it.

**Comment by jenzy** [comment]
This might already work, when upgrading to FlubuCore.Runner 2.2.1 i got this dialog:

![dialog](https://user-images.githubusercontent.com/6839802/34713285-0cbb054c-f526-11e7-9fd7-2ccb1544d6a1.PNG).

**Comment by mzorec** [comment]
The idea is that if build script file already exists you shouldn't even get this dialog. Nuget script should just skip copying template BuildScript.cs file.

**Comment by jenzy** [comment]
Yes, the `Install.ps1` could be modified to skip `BuildScript.cs` if it already exists. However, it turns out that the file conflict dialog occurs before the `Install.ps1` script is even run, when nuget is copying files from the packages directory to the project.  I don't think there is a way to influence that using just the installer script.

Example output of `Update-Package -Verbose`: https://pastebin.com/xQ7Lp9Ea

The odd thing is that besides for `BuildScript.cs` the file conflict dialog is also shown for `temp\build.exe.config` and `temp\build.exe`. These two files do not physically exist in the project before the update command has been run, yet nuget seems to think they do - possibly based on the contents of the previous package version.

**Comment by mzorec** [comment]
BuildScript.cs could be copied  to tmp directory by nuget installer(this is defined in nuspec file) like build.exe, build.exe.config and then copied to root of the project like other files with powershell script. But then there is another problem... On fresh install BuildScript.cs file is not included in project which i think is worse than a dialog box. 

You get conflict dialog box if tmp directory is still present in vs solution explorer even if files does not physically exist anymore. For example this happens if u install flubu  and then without refreshing solution explorer you update flubu nuget package.
